---
title: "How to moderate constructive debates?"
subtitle: "A timid and probably naive proposal"
author: "**Pietro Monticone**"
# date: "`r Sys.Date()`"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
#    toc: true
fontsize: 11pt
biblio-style: apalike
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


### **Description of the event**

* Title
* Subtitle
* Motion $P$ together with the aggregation procedure by which $P$ was constructed
* Names of PRO-$P$ panelists 
* Names of CON-$P$ panelists

### **Pre-Debate**

1. **Audience seats randomization** to minimize social biases (conformity, homophily, etc.)
2. **Vote**  on $P$ via web-based polling platform (e.g. [Mentimeter](https://www.mentimeter.com), [Poll Everywhere](https://www.polleverywhere.com), [Slido](https://www.sli.do))
    * PRO $=+1$
    * INDIFFERENT $=0$
    * CON $=-1$
3. Remind yourself and the audience of the **crucial distinction** between the *epistemic agent* provisionally believing $P$ and the *epistemic state* of believing $P$
4. Ask the panelists for an explicit commitment to the **Temporary Dogma of the Interlocutor's Intellectual Honesty (TDIIH)**: the first ethical assumption the panelists must accept and the last one they can reject in order to maximize the explorable volume in dialectic space (already strongly constrained by limited time and cognitive resources), thereby minimizing learning and agreement opportunity loss.
5. Ask the panelists for an explicit commitment to briefly **re-express the interlocutor's position** until it's been recognised as "fair characterization" by the interlocutor him/herself before starting to criticize it in order to ensure a minimum degree of *common knowledge*
6. Remind the panelists of the possibility of using the **Bullshit Bonus (BB)** based on the **Extended Bullshit Asymmetry Principle (EBAP)** ^["The amount of energy necessary to dismantle a bullshit is at least an order of magnitude bigger than to produce it." (See the original [**BAP**](https://twitter.com/ziobrando/status/289635060758507521?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E289635060758507521&ref_url=http%3A%2F%2Fordrespontane.blogspot.com%2F2014%2F07%2Fbrandolinis-law.html))]: Let's consider two epistemic agents $A$ and $B$ in free, dispassionate communication under the TDIIH regime
   * Agent $A$ expresses a collection of propositions $\{ P_i \}$
   * Agent $B$ believes that $\{ P_i \}$ could be classified as *bullshit* $\Rightarrow B$ has the right to ask for the extension of the available time to be at least one order of magnitude bigger than the time it took to generate the declared *bullshit*, then 
     * if $A$ is convinced of the refutation of $\{ P_i \}$ by $A \Rightarrow B$ accepts the criticism and proceeds considering $\{ P_i \}$ invalid ;
     * if $A$ is NOT convinced of the refutation of $\{ P_i \}$ by $A \Rightarrow A$ does NOT accept the criticism and gains $\Delta t$ equal to that spent by $B$ to try to dismantle $\{ P_i \}$ .

### **Debate** 

1. $\leq 15$ minutes of building PRO-$P$ arguments
2. $\leq 15$ minutes of building CON-$P$ arguments
3. $5$ minutes of (even anonymous) questions and comments from the public whose *social utility* will be estimated by the likes they get by the members of the same
4. $\leq 15$ minutes for PRO-$P$ panelists to tackle CON-$P$ arguments
5. $\leq 15$ minutes CON-$P$ panelists to tackle PRO-$P$ arguments
6. $40$ minutes of free panelist-panelist interaction + the presentation of the most voted questions
7. Final statements of the panelists

### **Post-Debate**
1. **Vote**
    * PRO $=+1$
    * INDIFFERENT $=0$
    * CON $=-1$

2. **The winners are** the *state* with the highest number of post-debate votes **and** the *agents* with the greatest $\Delta = V_{post}-V_{pre}$. ^[In order to stress once again that the *proposition* winning is not the same as the *agent* winning.]
